id: IC421942A
initial_creation_type: ebook
source_metadata:
  id: MIN-TC-13
  title: ༄༅།  །གནས་རྟེན་གྱི་ཆེ་བརྗོད་དཀར་ཆག་གནས་ལུགས་རབ་ཏུ་གསལ་བའི་མེ་ལོང་ཞེས་བྱ་བ་བཞུགས་སོ།  །
  author: མཛད་པ་པོ། སྨིན་གླིང་གཏེར་ཆེན་འགྱུར་མེད་རྡོ་རྗེ།
  authors: &id001
  - མཛད་པ་པོ། སྨིན་གླིང་གཏེར་ཆེན་འགྱུར་མེད་རྡོ་རྗེ།
  sku: MIN-TC-13
  cover: MIN-TC-13.jpg
  volume: {}
ebook_metadata:
  title: ༄༅།  །གནས་རྟེན་གྱི་ཆེ་བརྗོད་དཀར་ཆག་གནས་ལུགས་རབ་ཏུ་གསལ་བའི་མེ་ལོང་ཞེས་བྱ་བ་བཞུགས་སོ།  །
  authors: *id001
  sku: MIN-TC-13
  cover: MIN-TC-13.jpg
layers:
- Author
- BookTitle
- Chapter
- Commentary
- Yigchung
